package smiteapi

type God struct {
	Ability1                   string
	Ability2                   string
	Ability3                   string
	Ability4                   string
	Ability5                   string
	AbilityId1                 int
	AbilityId2                 int
	AbilityId3                 int
	AbilityId4                 int
	AbilityId5                 int
	AttackSpeed                float32
	AttackSpeedPerLevel        float32
	Cons                       string
	HP5PerLevel                float32
	Health                     int
	HealthPerFive              int
	HealthPerLevel             int
	Item1                      string
	Item2                      string
	Item3                      string
	Item4                      string
	Item5                      string
	Item6                      string
	Item7                      string
	Item8                      string
	Item9                      string
	ItemId1                    int
	ItemId2                    int
	ItemId3                    int
	ItemId4                    int
	ItemId5                    int
	ItemId6                    int
	ItemId7                    int
	ItemId8                    int
	ItemId9                    int
	Lore                       string
	MP5PerLevel                float32
	MagicProtection            int
	MagicProtectionPerLevel    float32
	Mana                       int
	ManaPerFive                float32
	ManaPerLevel               int
	Name                       string
	OnFreeRotation             string
	Pantheon                   string
	PhysicalPower              int
	PhysicalPowerPerLevel      float32
	PhysicalProtection         int
	PhysicalProtectionPerLevel float32
	Pros                       string
	Roles                      string
	Speed                      int
	Title                      string
	Type                       string
}
